name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: ['23.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: pnpm install --frozen-lockfile
    - run: pnpm lint
    - run: pnpm build
#    - run: pnpm test
