name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: ['23.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Lint check
      run: pnpm lint
    - name: Build
      run: pnpm build
#    - name: Test
#      run: pnpm test
